name: Practica Inicial Actions

on:
  workflow_dispatch:
    inputs:
      saludo:
        description: 'Mensaje a mostrar'
        required: true
        default: 'Aprendiendo Actions!'
        type: string

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar Mensaje
        run: |
          echo "El mensaje ingresado fue:"
          echo "${{ inputs.saludo }}"
          echo "Workflow ejecutado por: ${{ github.actor }}"